services:
  - type: web
    name: faithchat-api
    rootDir: backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        fromService:
          name: faithchat-web
          type: static_site
          property: url
    healthCheckPath: /healthz
    autoDeploy: true

  - type: static_site
    name: faithchat-web
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          name: faithchat-api
          type: web
          property: url
